### ISSUE TITLE
Chrome browser load errors (works in Firefox)

### ISSUE THREAD

**Issue by ghost** [2003scape/rsc-client#6]
Cloned the repo, ran ```npm install``` (the command listed in readme of ```npm install @2003scape/rsc-client``` does not work)
```
root@e6fecf74f7af:/var/www/html/rsc-client# npm install @2003scape/rsc-client
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@2003scape%2frsc-client - Not found
npm ERR! 404
npm ERR! 404  '@2003scape/rsc-client@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T15_19_49_108Z-debug.log
```

then I ran ```npm start```
```
root@e6fecf74f7af:/var/www/html/rsc-client# npm start

> @2003scape/rsc-client@1.0.0 start /var/www/html/rsc-client
> st -p 1337 -d dist

listening at http://[::]:1337
```

Navigating to http://localhost:1337/index.html#members,127.0.0.1,43595 results in its starting to load, then turning into a black screen. I'm seeing this in the Chrome browser console when trying to load from a Dockerized node instance:
![image](https://user-images.githubusercontent.com/16737510/96893106-5a530580-1458-11eb-92bb-3103fa4a5af3.png)

**Comment by misterhat** [comment]
fixed in https://github.com/2003scape/rsc-client/commit/852eba3811aef274e4380ccbff58fd704a9b965f
